#!/bin/sh

declare options=("Connect
Pair
Scan
Discoverable
Pairable
")

choice=$(echo -e "${options[@]}" | dmenu -i -h 30 -p 'What would you like to do: ')

# device=$(echo "devices" | bluetoothctl | awk '$1 == "Device"' | 
#     dmenu -i -h 30 -p 'Pick a device: ' | awk -F' ' '{print $2}')

case "$choice" in
    Connect)
        perform="connect $(echo "devices" | bluetoothctl | awk '$1 == "Device"' | 
    dmenu -i -h 30 -p 'Pick a device: ' | awk -F' ' '{print $2}')"
    ;;
    Pair)
        perform="pair $(echo "devices" | bluetoothctl | awk '$1 == "Device"' | 
    dmenu -i -h 30 -p 'Pick a device: ' | awk -F' ' '{print $2}')"
        notify-send "Bluetooth Pairing" "$(bluetoothctl $perform)"
    ;;
    Scan)
        perform="scan on"
    ;;
    Discoverable)
        perform="discoverable on"
        notify-send "Bluetooth Discoverable" "$(bluetoothctl $perform)"
    ;;
    Pairable)
        perform="pairable on"
        notify-send "Bluetooth Pairable" "$(bluetoothctl $perform)"
    ;;
    *)
        exit 1
    ;;
esac

$TERMINAL -e bluetoothctl $perform
