#!/bin/sh

declare options=("zsh
neovim
sxhkd
bspwm
xresources
polybar
lf")

choice=$(echo -e "${options[@]}" | dmenu -i -h 30 -p 'Edit config file: ')

case "$choice" in
    zsh)
        choice="$HOME/.zshrc"
    ;;
    neovim)
        choice="$HOME/.config/nvim/init.vim"
    ;;
    sxhkd)
        choice="$HOME/.config/sxhkd/sxhkdrc"
    ;;
    bspwm)
        choice="$HOME/.config/bspwm/bspwmrc"
    ;;
    xresources)
        choice="$HOME/.Xresources"
    ;;
    polybar)
        choice="$HOME/.config/polybar/config"
    ;;
    lf)
        choice="$HOME/.config/lf/lfrc"
    ;;
    *)
        exit 1
    ;;
esac

nvim "$choice"
