#!/bin/bash

choice="$(rofi -dmenu -i -p "Edit config file: " << !
zsh
env
neovim
xresources
polybar
lf
aliases
alacritty
!
)"

case "$choice" in
    zsh)
        choice="$HOME/.zshrc"
    ;;
    env)
        choice="$HOME/.zshenv"
    ;;
    neovim)
        choice="$HOME/.config/nvim/init.vim"
    ;;
    xresources)
        choice="$HOME/.Xresources"
    ;;
    polybar)
        choice="$HOME/.config/polybar/config"
    ;;
    aliases)
        choice="$HOME/.config/.aliases"
    ;;
    alacritty)
        choice="$HOME/.config/alacritty/alacritty.yml"
    ;;
    *)
        exit 1
    ;;
esac

nvim "$choice"
