#!/bin/sh
userid=$(id -u)
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$userid/bus"
export DBUS_SESSION_BUS_ADDRESS
/usr/bin/notify-send -t 3000 "Daily Message" "Pray for Purity and Take Supplements"
