#!/bin/bash
v4l2-ctl \
    --set-ctrl=brightness=159 \
    --set-ctrl=contrast=138 \
    --set-ctrl=saturation=132 \
    --set-ctrl=white_balance_temperature=6367 \
    --set-ctrl=exposure_auto=1 \
    --set-ctrl=exposure_absolute=750 \
    --set-ctrl=focus_auto=0 \
    --set-ctrl=zoom_absolute=112 \
