#!/bin/sh

case $HOSTNAME in
    (archmain) cp -f ~/.config/alacritty/alacrittymain.yml ~/.config/alacritty/alacritty.yml && cp -f ~/.config/rofi/configmain.rasi ~/.config/rofi/config.rasi;;
    (archthink) cp -f ~/.config/alacritty/alacrittythink.yml ~/.config/alacritty/alacritty.yml && cp -f ~/.config/rofi/configthink.rasi ~/.config/rofi/config.rasi;;
esac
