#!/bin/bash

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

case "$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)" | rofi -dmenu -lines 6 -i -p "Screenshot which area?")" in
    "a selected area") path="~/shots/pic-selected-'$(date +%y%m%d-%H%M)'" && 
        maim -s "$path" &&
        xclip -selection clipboard -t image/png "$path"  ;;
	"current window") path="~/shots/pic-window-'$(date +%y%m%d-%H%M-%S).png'" &&
        maim -i "$(xdotool getactivewindow)" &&
        xclip -selection clipboard -t image/png "$path";;
	"full screen") path="~/shots/pic-full-'$(date +%y%m%d-%H%M-%S)'.png" &&
        maim &&
        xclip -selection clipboard -t image/png "$path";;
esac
