#!/bin/bash

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

case "$(printf "a selected area\\ncurrent window\\nfull screen" | rofi -dmenu -lines 6 -i -p "Screenshot which area?")" in
    "a selected area") path="$HOME/shots/pic-selected-$(date +%y%m%d-%H%M-%S)" && 
        maim -s $path &&
        xclip -selection clipboard -t image/png "$path"  ;;
	"current window") path="$HOME/shots/pic-window-$(date +%y%m%d-%H%M-%S).png" &&
        maim -i $(xdotool getactivewindow) $path &&
        xclip -selection clipboard -t image/png $path;;
	"full screen") path="$HOME/shots/pic-full-$(date +%y%m%d-%H%M-%S).png" &&
        maim $path &&
        xclip -selection clipboard -t image/png "$path";;
esac
