#!/bin/sh

# Terminate existing instances
killall -q polybar

# Wait for all processes to shut down
while pgrep -u $(id -ru) -x polybar > /dev/null; do
sleep 1; done

# Launch polybar
case $HOSTNAME in
    (archmain) polybar example -r &;;
    (archthink) polybar example -r &;;
esac
