#!/bin/sh

export GTK_IM_MODULE=IBus
export QT_IM_MODULE=fcitx5

case $HOSTNAME in
    (archmain) cp -f ~/.config/alacritty/alacrittymain.yml ~/.config/alacritty/alacritty.yml &&
        exec sway ;;
    (archthink) cp -f ~/.config/alacritty/alacrittythink.yml ~/.config/alacritty/alacritty.yml && 
        exec sway ;;
esac
